version: '3.9'

services:
  app:
    image: node:latest
    tty: true
    stdin_open: true
    container_name: api-lootlab
    working_dir: /src
    depends_on:
      - api-lootlab-postgresql
    ports:
      - 3333:3333
    environment:
      - node=dev
      - url=postgresql://docker:docker@api-lootlab-postgresql:5432/lootlab?schema=public
    volumes:
      - ./:/src
    command: >
      sh -c "npm install && npx prisma migrate deploy && npm run start"
    
  api-lootlab-postgresql:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=lootlab
